services:
  reverse-proxy:
    image: traefik:v3.6
    environment:
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    ports:
    # HTTP
      - "80:80"
    # HTTPS
      - "443:443"
    # Traefik Web UI
      - "8080:8080"
    volumes:
      - letsencrypt:/letsencrypt
      - /var/run/docker.sock:/var/run/docker.sock
      - ./traefik.yaml:/etc/traefik/traefik.yaml:ro
  server:
    image: ghcr.io/kaldis-berzins/cv-website:main
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv-website.rule=Host(`kaldisberzins.com`)"
      - "traefik.http.routers.cv-website.entrypoints=websecure"
      - "traefik.http.routers.cv-website.tls.certresolver=myresolver"
  obsidian-livesync:
    image: couchdb:3.1.2
    ports:
      - "5984:5984"
    environment:
      - COUCHDB_USER=${COUCHDB_USER}
      - COUCHDB_PASSWORD=${COUCHDB_PASSWORD}
    volumes:
      - ./data/couchdb:/opt/couchdb/data
      - ./conf/local.ini:/opt/couchdb/etc/local.ini
      - ./local.d:/opt/couchdb/etc/local.d
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.obsidian.rule=Host(`obsidian.kaldisberzins.com`)"
      - "traefik.http.routers.obsidian.entrypoints=websecure"
      - "traefik.http.routers.obsidian.tls.certresolver=myresolver"
      - "traefik.http.services.obsidian.loadbalancer.server.port=5984"
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: tmcdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d tmcdb"]
      interval: 5s
      timeout: 5s
      retries: 10

  app:
    image: ghcr.io/kaldis-berzins/tmcdb:master
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.cv-website.rule=Host(`tmcdb.kaldisberzins.com`)"
      - "traefik.http.routers.cv-website.entrypoints=websecure"
      - "traefik.http.routers.cv-website.tls.certresolver=myresolver"
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/tmcdb?schema=public
      NODE_ENV: production
      PORT: 3000
      HOST: 0.0.0.0
      OPENAI_API_KEY: ${OPENAI_API_KEY}
    depends_on:
      db:
        condition: service_healthy
volumes:
  letsencrypt: